version: "3.9"
services:
  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: todoapp_graphql
      POSTGRES_USER: todoapp_graphql
      POSTGRES_DB: todoapp_graphql
    ports:
      - 5432:5432
  postgres_test:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: todoapp_graphql_test
      POSTGRES_USER: todoapp_graphql_test
      POSTGRES_DB: todoapp_graphql_test
    ports:
      - 5433:5432
