POSTGRES_CONTAINER_NAME := todoapp_graphql_postgres
POSTGRES_USER := todoapp_graphql
POSTGRES_PASSWORD := todoapp_graphql
POSTGRES_DB := todoapp_graphql
POSTGRES_PORT := 5432
DATABASE_URL := postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@localhost:$(POSTGRES_PORT)/$(POSTGRES_DB)
# for Figment config
APP_DATABASE__URL := $(DATABASE_URL)

export POSTGRES_CONTAINER_NAME POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB POSTGRES_PORT DATABASE_URL APP_DATABASE__URL

.PHONY: start
start:
	mprocs 
